### ISSUE TITLE
How to test segmented_cache  with ProPER?

### ISSUE THREAD

**Issue by Zabrane** [esl/segmented_cache#15]
Hi @NelsonVides 

I'd like to test [segmented_cache_proper_commands.erl](https://github.com/esl/segmented_cache/blob/main/test/segmented_cache_proper_commands.erl) with ProPER. 

Which command should I use?
Many thanks

my config: Erlang 25 on macOS Sonoma

**Comment by NelsonVides** [comment]
Hey there :)

I'd usually do `rebar3 ct`, or even more precisely `rebar3 ct --suite test/segmented_cache_SUITE.erl --group basic_api --case stateful_property`, as here PropEr runs directly within common tests.

Let me know if it works!

**Comment by Zabrane** [comment]
@NelsonVides Thanks a lot. It worked as expected.
